[package]
name = "algorithm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "p5"

[[bin]]
name = "p6"

[[bin]]
name = "p7"

[[bin]]
name = "p8"

[[bin]]
name = "p9"

[[bin]]
name = "p16"

[[bin]]
name = "p17"

[dependencies]
